### ISSUE TITLE
Terrform Licensing

### ISSUE THREAD

**Issue by skorfmann** [winglang/wing-github-action#62]
HashiCorp published [FAQ](https://www.hashicorp.com/blog/hashicorp-updates-licensing-faq-based-on-community-questions) around the BSL licensing change for their products including Terraform. 

> Q: What is a “competitive offering” under the HashiCorp BSL license?
> 
> ... By contrast, products that are not sold or supported on a paid basis are always allowed under the HashiCorp BSL license because they are not considered competitive.
>
> Q: What does the term “embedded” mean under the HashiCorp BSL license?
>
> A: Under the HashiCorp BSL license, the term “embedded” means including the source code or object code, including executable binaries, from a HashiCorp product in a competitive product. “Embedded” also means packaging the competitive product in such a way that the HashiCorp product must be accessed or downloaded for the competitive product to operate.

Judging by this excerpt I'd say: 

1. This Github Actions is embedding the Terraform binary 
2. It's not a competitive offering, since it's not sold or commercially supported 

However, I'm not a lawyer - so it'd be good to get this checked somehow. 

Until further clarification, we definitely should stay at the `1.5` version of Terraform.

**Comment by ekeren** [comment]
I agree that we are not offering any competitive offering -  since it’s not sold or commercially supported

I don't think we should have this restriction (for now) 


@ShaiBer, any objection?

**Comment by ShaiBer** [comment]
no objections. Closing for now
